global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]
    metrics_path: /metrics

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8080"]
    metrics_path: /metrics

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8080"]
    metrics_path: /metrics

  - job_name: "merchant-service"
    static_configs:
      - targets: ["merchant-service:8080"]
    metrics_path: /metrics

  - job_name: "fraud-service"
    static_configs:
      - targets: ["fraud-service:8080"]
    metrics_path: /metrics

  - job_name: "settlement-service"
    static_configs:
      - targets: ["settlement-service:8080"]
    metrics_path: /metrics

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
